server:
  port: ${SERVER_PORT:8096}

spring:
  application:
    name: account-recipients
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jcondotta.banking.*"
        spring.json.write-dates-as-timestamps: false
        spring.json.value.default.type: com.jcondotta.banking.contracts.activate.BankAccountActivatedIntegrationEvent

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}
    dynamodb:
      tables:
        account-recipients:
          table-name: ${AWS_DYNAMODB_ACCOUNT_RECIPIENTS_TABLE_NAME}

app:
  environment: ${APPLICATION_ENV}
  api:
    v1:
      recipients:
        root-path: '/api/v1/bank-accounts/{bank-account-id}/recipients'
        recipient-id-path: '/api/v1/bank-accounts/{bank-account-id}/recipients/{recipient-id}'
  kafka:
    topics:
      bank-account-activated:
        topic-name: ${KAFKA_BANK_ACCOUNT_ACTIVATED_TOPIC_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true
        bankaccount.*: true

      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        bankaccount.*: 0.5, 0.95, 0.99